version: '3'
services:
  webserver:
    image: nginx:alpine
    container_name: "${APP_URL:-ci3-docker.app}"
    restart: unless-stopped
    tty: true
    ports:
      - "${FORWARD_APP_PORT:-8080}:${APP_PORT:-80}"
    volumes:
      - ./:/var/www/public
      - ./config/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
  
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "${PHP_VERSION:-7.4.30}"
    image: "${APP_URL:-ci3-docker.app}/php"
    container_name: "${APP_NAME:-ci3-docker}"
    working_dir: /var/www/public
    volumes:
      - ./:/var/www/public
    networks:
      - app-network
    links:
      - db
    depends_on:
      - db

  db:
    image: "mysql:${mysql_VERSION:-8.0.30}"
    container_name: "${DB_HOST:-ci3-docker-db}"
    restart: unless-stopped
    tty: true
    ports:
      - "${FORWARD_DB_PORT:-3307}:${DB_PORT:-3306}"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_DATABASE: "${DB_DATABASE:-ci3-docker_dev}"
      MYSQL_USER: "${DB_USERNAME:-docker}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      SERVICE_TAGS: dev
    volumes:
      - dbdata:/var/lib/mysql/
      - ./config/mysql/db:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local